version: '3'
services:
  php:
    build: ./php
    user: "1000:1000"
    ports:
      - "80:80"
    volumes:
      - ./public_html:/var/www/html
    links:
      - mysql
  mysql:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sss
    volumes:
      - ./mysql/data:/var/lib/mysql